### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by mogambro** [Defernus/bevy-voxel-engine#2]
Hello!

This is a very cool project you created here. Thanks for sharing it!
What is missing is a license so potential contributors know what they sign up for.

Best regards,
Tom

**Comment by TheDan64** [comment]
MIT/Apache perhaps?

**Comment by Rainy-Afternoon** [comment]
It'll be nice to have a license because I've been wanting to use this for a game but I'm scared to use it since there's no license.

**Comment by gituseridk** [comment]
Done
